# Generated by Django 5.1.3 on 2024-11-21 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boatModel', models.CharField(max_length=100)),
                ('productionYear', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('draft', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('pricePerDay', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('places', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('price', models.IntegerField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChartersDatabase.boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='motherPort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ChartersDatabase.port'),
        ),
    ]
