# Generated by Django 5.1.3 on 2024-11-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartersDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='motherPort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ChartersDatabase.port'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='places',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
