# Generated by Django 5.1.3 on 2024-11-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChartersDatabase', '0002_alter_boat_motherport_alter_boat_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='motherPort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ChartersDatabase.port'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
